### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Ramsdorf** [epicf/ef#22]
After entering of:
git clone https://github.com/epicf/ef your-ef-dir
The terminal answers:
Command 'git' not found but can be installed with:
sudo apt install git

**Comment by dumbman** [comment]
нужно git установить командой
sudo apt-get install git

**Comment by fizmat** [comment]
The command to install git depends on user's OS distribution and user preference (apt/apt-get/aptitude/... on Debian or Ubuntu derivatives, yum on RedHat derivatives, pacman on Arch, etc.).
I don't think it's worthwhile to explain every way to install git. We could add "you need to have git to clone git repositories" to the manual, but it sounds sarcastic and condescending...
