### ISSUE TITLE
Test of Example "Single Particle In Uniform Electric Field" 

### ISSUE THREAD

**Issue by Ramsdorf** [epicf/ef#23]
Calculated results are different from the results shown in Wiki:
![image](https://user-images.githubusercontent.com/47527233/52781487-c7947d80-305d-11e9-9ff2-7581c4acaaf3.png) 
![image](https://user-images.githubusercontent.com/47527233/52781693-3e317b00-305e-11e9-9c68-3e7243754b3e.png)

**Comment by dumbman** [comment]
I have changed number of iteration from 150 to 2000 in filed_solver.cpp. Now it is better 
![2d](https://user-images.githubusercontent.com/9937069/52782238-9fa61980-305f-11e9-96f0-1b119dc613f5.png)
